[server]
user = "username"  # SSH user for the target server
addr = "127.0.0.1" # target server address

[services.llm]
remote_ports = "8080-8089" # Remote ports to forward
local_ports = "8080-8089"  # Local ports to forward
